dimensions = [
    "day",
    "app",
    "app_token",
    "country_code",
    "country",
    "currency_code",
    "currency",
    "os_name",
    "campaign_id_network",
    "campaign_network",
    "adgroup_id_network",
    "adgroup_network",
    "creative_id_network",
    "creative_network",
    "network",
]

conversion_metrics_list = [
    "click_conversion_rate",
    "gdpr_forgets",
    "impression_conversion_rate",
    "limit_ad_tracking_installs",
    "limit_ad_tracking_install_rate",
    "limit_ad_tracking_reattribution_rate",
    "limit_ad_tracking_reattributions",
    "maus",
    "reattributions",
]

ad_spend_metrics_list = [
    "click_cost",
    "cost",
    "ecpc",
    "ecpi",
    "ecpm",
    "impression_cost",
    "install_cost",
    "paid_clicks",
    "paid_impressions",
    "paid_installs",
]

revenue_metrics_list = [
    "all_revenue",
    "cohort_ad_revenue",
    "cohort_all_revenue",
    "cohort_gross_profit",
    "cohort_revenue",
    "return_on_investment",
    "revenue_to_cost",
    "revenue",
    "revenue_est",
    "revenue_max",
    "revenue_min",
    "roas",
]

skad_metrics_list = [
    "conversion_value_total",
    "skad_conversion_value_gt_0",
    "skad_conversion_value_null",
    "skad_installs",
    "skad_qualifiers",
    "skad_reinstalls",
    "skad_total_installs",
    "invalid_payloads",
    "valid_conversions",
    "waus",
    "conversion_1",
    "conversion_2",
    "conversion_3",
    "conversion_4",
    "conversion_5",
    "conversion_6",
]

event_metrics = [
    "onboarding_completed",
    "purchase_maps",
    "purchase_premium",
    "sign_up",
    "sports_selected",
    "use_route",
]

event_metrics_suffix = [
    "events",
    "events_min",
    "events_max",
    "events_est",
    "revenue",
    "revenue_min",
    "revenue_max",
    "revenue_est",
]

event_metrics_list = [f"{metric}_{suffix}" for metric in event_metrics for suffix in event_metrics_suffix]

conversion_long_metrics_list = [
    # "conversion_value_0",
    # "conversion_value_1",
    # "conversion_value_2",
    # "conversion_value_3",
    # "conversion_value_4",
    # "conversion_value_5",
    # "conversion_value_6",
    # "conversion_value_7",
    # "conversion_value_8",
    # "conversion_value_9",
    # "conversion_value_10",
    # "conversion_value_11",
    # "conversion_value_12",
    # "conversion_value_13",
    # "conversion_value_14",
    # "conversion_value_15",
    # "conversion_value_16",
    # "conversion_value_17",
    # "conversion_value_18",
    # "conversion_value_19",
    # "conversion_value_20",
    # "conversion_value_21",
    # "conversion_value_22",
    # "conversion_value_23",
    # "conversion_value_24",
    # "conversion_value_25",
    # "conversion_value_26",
    # "conversion_value_27",
    # "conversion_value_28",
    # "conversion_value_29",
    # "conversion_value_30",
    # "conversion_value_31",
    # "conversion_value_32",
    # "conversion_value_33",
    # "conversion_value_34",
    # "conversion_value_35",
    # "conversion_value_36",
    # "conversion_value_37",
    # "conversion_value_38",
    # "conversion_value_39",
    # "conversion_value_40",
    # "conversion_value_41",
    # "conversion_value_42",
    # "conversion_value_43",
    # "conversion_value_44",
    # "conversion_value_45",
    # "conversion_value_46",
    # "conversion_value_47",
    # "conversion_value_48",
    # "conversion_value_49",
    # "conversion_value_50",
    # "conversion_value_51",
    # "conversion_value_52",
    # "conversion_value_53",
    # "conversion_value_54",
    # "conversion_value_55",
    # "conversion_value_56",
    # "conversion_value_57",
    # "conversion_value_58",
    # "conversion_value_59",
    # "conversion_value_60",
    # "conversion_value_61",
    # "conversion_value_62",
    # "conversion_value_63",
]
